try{
    aler("this is error to catch");
}catch(e){
    console.log('this is not error');

}